//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActClass">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="ACCM"/>
 *     <enumeration value="ACCT"/>
 *     <enumeration value="ACSN"/>
 *     <enumeration value="ACT"/>
 *     <enumeration value="ACTN"/>
 *     <enumeration value="ADJUD"/>
 *     <enumeration value="AEXPOS"/>
 *     <enumeration value="ALRT"/>
 *     <enumeration value="BATTERY"/>
 *     <enumeration value="CACT"/>
 *     <enumeration value="CASE"/>
 *     <enumeration value="CATEGORY"/>
 *     <enumeration value="CDALVLONE"/>
 *     <enumeration value="CLNTRL"/>
 *     <enumeration value="CLUSTER"/>
 *     <enumeration value="CNOD"/>
 *     <enumeration value="CNTRCT"/>
 *     <enumeration value="COMPOSITION"/>
 *     <enumeration value="CONC"/>
 *     <enumeration value="COND"/>
 *     <enumeration value="CONS"/>
 *     <enumeration value="CONTAINER"/>
 *     <enumeration value="CONTREG"/>
 *     <enumeration value="COV"/>
 *     <enumeration value="CTTEVENT"/>
 *     <enumeration value="DETPOL"/>
 *     <enumeration value="DGIMG"/>
 *     <enumeration value="DIET"/>
 *     <enumeration value="DISPACT"/>
 *     <enumeration value="DOC"/>
 *     <enumeration value="DOCBODY"/>
 *     <enumeration value="DOCCLIN"/>
 *     <enumeration value="DOCSECT"/>
 *     <enumeration value="EHR"/>
 *     <enumeration value="ENC"/>
 *     <enumeration value="EXP"/>
 *     <enumeration value="EXPOS"/>
 *     <enumeration value="EXTRACT"/>
 *     <enumeration value="FCNTRCT"/>
 *     <enumeration value="FOLDER"/>
 *     <enumeration value="GEN"/>
 *     <enumeration value="GROUPER"/>
 *     <enumeration value="INC"/>
 *     <enumeration value="INFO"/>
 *     <enumeration value="INFRM"/>
 *     <enumeration value="INVE"/>
 *     <enumeration value="INVSTG"/>
 *     <enumeration value="JURISPOL"/>
 *     <enumeration value="LIST"/>
 *     <enumeration value="LLD"/>
 *     <enumeration value="LOC"/>
 *     <enumeration value="MPROT"/>
 *     <enumeration value="OBS"/>
 *     <enumeration value="OBSCOR"/>
 *     <enumeration value="OBSSER"/>
 *     <enumeration value="ORGPOL"/>
 *     <enumeration value="OUTB"/>
 *     <enumeration value="PCPR"/>
 *     <enumeration value="PHN"/>
 *     <enumeration value="POL"/>
 *     <enumeration value="POLICY"/>
 *     <enumeration value="POS"/>
 *     <enumeration value="POSACC"/>
 *     <enumeration value="POSCOORD"/>
 *     <enumeration value="PRN"/>
 *     <enumeration value="PROC"/>
 *     <enumeration value="REG"/>
 *     <enumeration value="REV"/>
 *     <enumeration value="RLD"/>
 *     <enumeration value="ROIBND"/>
 *     <enumeration value="ROIOVL"/>
 *     <enumeration value="RTRD"/>
 *     <enumeration value="SBADM"/>
 *     <enumeration value="SBEXT"/>
 *     <enumeration value="SCOPOL"/>
 *     <enumeration value="SEQ"/>
 *     <enumeration value="SEQVAR"/>
 *     <enumeration value="SFWL"/>
 *     <enumeration value="SIT"/>
 *     <enumeration value="SPCOBS"/>
 *     <enumeration value="SPCTRT"/>
 *     <enumeration value="SPECCOLLECT"/>
 *     <enumeration value="SPLY"/>
 *     <enumeration value="STC"/>
 *     <enumeration value="STDPOL"/>
 *     <enumeration value="STN"/>
 *     <enumeration value="STORE"/>
 *     <enumeration value="SUBST"/>
 *     <enumeration value="SUP"/>
 *     <enumeration value="TEXPOS"/>
 *     <enumeration value="TOPIC"/>
 *     <enumeration value="TRD"/>
 *     <enumeration value="TRFR"/>
 *     <enumeration value="TRNS"/>
 *     <enumeration value="VERIF"/>
 *     <enumeration value="XACT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActClass")
@XmlEnum
public enum ActClass {

    ACCM,
    ACCT,
    ACSN,
    ACT,
    ACTN,
    ADJUD,
    AEXPOS,
    ALRT,
    BATTERY,
    CACT,
    CASE,
    CATEGORY,
    CDALVLONE,
    CLNTRL,
    CLUSTER,
    CNOD,
    CNTRCT,
    COMPOSITION,
    CONC,
    COND,
    CONS,
    CONTAINER,
    CONTREG,
    COV,
    CTTEVENT,
    DETPOL,
    DGIMG,
    DIET,
    DISPACT,
    DOC,
    DOCBODY,
    DOCCLIN,
    DOCSECT,
    EHR,
    ENC,
    EXP,
    EXPOS,
    EXTRACT,
    FCNTRCT,
    FOLDER,
    GEN,
    GROUPER,
    INC,
    INFO,
    INFRM,
    INVE,
    INVSTG,
    JURISPOL,
    LIST,
    LLD,
    LOC,
    MPROT,
    OBS,
    OBSCOR,
    OBSSER,
    ORGPOL,
    OUTB,
    PCPR,
    PHN,
    POL,
    POLICY,
    POS,
    POSACC,
    POSCOORD,
    PRN,
    PROC,
    REG,
    REV,
    RLD,
    ROIBND,
    ROIOVL,
    RTRD,
    SBADM,
    SBEXT,
    SCOPOL,
    SEQ,
    SEQVAR,
    SFWL,
    SIT,
    SPCOBS,
    SPCTRT,
    SPECCOLLECT,
    SPLY,
    STC,
    STDPOL,
    STN,
    STORE,
    SUBST,
    SUP,
    TEXPOS,
    TOPIC,
    TRD,
    TRFR,
    TRNS,
    VERIF,
    XACT;

    public String value() {
        return name();
    }

    public static ActClass fromValue(String v) {
        return valueOf(v);
    }

}
