//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActClassGenomicObservation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActClassGenomicObservation">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="GEN"/>
 *     <enumeration value="DETPOL"/>
 *     <enumeration value="EXP"/>
 *     <enumeration value="LOC"/>
 *     <enumeration value="PHN"/>
 *     <enumeration value="POL"/>
 *     <enumeration value="SEQ"/>
 *     <enumeration value="SEQVAR"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActClassGenomicObservation")
@XmlEnum
public enum ActClassGenomicObservation {

    GEN,
    DETPOL,
    EXP,
    LOC,
    PHN,
    POL,
    SEQ,
    SEQVAR;

    public String value() {
        return name();
    }

    public static ActClassGenomicObservation fromValue(String v) {
        return valueOf(v);
    }

}
