//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActClassContainer.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActClassContainer">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CONTAINER"/>
 *     <enumeration value="CATEGORY"/>
 *     <enumeration value="DOCBODY"/>
 *     <enumeration value="DOCSECT"/>
 *     <enumeration value="TOPIC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActClassContainer")
@XmlEnum
public enum ActClassContainer {

    CONTAINER,
    CATEGORY,
    DOCBODY,
    DOCSECT,
    TOPIC;

    public String value() {
        return name();
    }

    public static ActClassContainer fromValue(String v) {
        return valueOf(v);
    }

}
