//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActRelationshipSequel.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActRelationshipSequel">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="SEQL"/>
 *     <enumeration value="APND"/>
 *     <enumeration value="BSLN"/>
 *     <enumeration value="COMPLY"/>
 *     <enumeration value="DOC"/>
 *     <enumeration value="FLFS"/>
 *     <enumeration value="OCCR"/>
 *     <enumeration value="OREF"/>
 *     <enumeration value="SCH"/>
 *     <enumeration value="GEN"/>
 *     <enumeration value="GEVL"/>
 *     <enumeration value="INST"/>
 *     <enumeration value="MOD"/>
 *     <enumeration value="MTCH"/>
 *     <enumeration value="OPTN"/>
 *     <enumeration value="RCHAL"/>
 *     <enumeration value="REV"/>
 *     <enumeration value="RPLC"/>
 *     <enumeration value="SUCC"/>
 *     <enumeration value="UPDT"/>
 *     <enumeration value="XCRPT"/>
 *     <enumeration value="VRXCRPT"/>
 *     <enumeration value="XFRM"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActRelationshipSequel")
@XmlEnum
public enum ActRelationshipSequel {

    SEQL,
    APND,
    BSLN,
    COMPLY,
    DOC,
    FLFS,
    OCCR,
    OREF,
    SCH,
    GEN,
    GEVL,
    INST,
    MOD,
    MTCH,
    OPTN,
    RCHAL,
    REV,
    RPLC,
    SUCC,
    UPDT,
    XCRPT,
    VRXCRPT,
    XFRM;

    public String value() {
        return name();
    }

    public static ActRelationshipSequel fromValue(String v) {
        return valueOf(v);
    }

}
