//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActRelationshipTemporallyPertains.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActRelationshipTemporallyPertains">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="OVERLAP"/>
 *     <enumeration value="OVERLAP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActRelationshipTemporallyPertains")
@XmlEnum
public enum ActRelationshipTemporallyPertains {

    EAE,
    EAS,
    EDU,
    EBS,
    ECW,
    CONCURRENT,
    SAE,
    SAS,
    SDU,
    SBS,
    SCW,
    DURING,
    OVERLAP;

    public String value() {
        return name();
    }

    public static ActRelationshipTemporallyPertains fromValue(String v) {
        return valueOf(v);
    }

}
