//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActRelationshipReason.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActRelationshipReason">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="RSON"/>
 *     <enumeration value="BLOCK"/>
 *     <enumeration value="CURE"/>
 *     <enumeration value="CURE.ADJ"/>
 *     <enumeration value="DIAG"/>
 *     <enumeration value="MITGT"/>
 *     <enumeration value="RCVY"/>
 *     <enumeration value="MTGT.ADJ"/>
 *     <enumeration value="SYMP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActRelationshipReason")
@XmlEnum
public enum ActRelationshipReason {

    RSON("RSON"),
    BLOCK("BLOCK"),
    CURE("CURE"),
    @XmlEnumValue("CURE.ADJ")
    CURE_ADJ("CURE.ADJ"),
    DIAG("DIAG"),
    MITGT("MITGT"),
    RCVY("RCVY"),
    @XmlEnumValue("MTGT.ADJ")
    MTGT_ADJ("MTGT.ADJ"),
    SYMP("SYMP");
    private final String value;

    ActRelationshipReason(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActRelationshipReason fromValue(String v) {
        for (ActRelationshipReason c: ActRelationshipReason.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
