//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActRelationshipPertains.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ActRelationshipPertains">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="PERT"/>
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="OVERLAP"/>
 *     <enumeration value="OVERLAP"/>
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="EAE"/>
 *     <enumeration value="EAS"/>
 *     <enumeration value="EDU"/>
 *     <enumeration value="EBS"/>
 *     <enumeration value="ECW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="SAE"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SDU"/>
 *     <enumeration value="SBS"/>
 *     <enumeration value="SCW"/>
 *     <enumeration value="CONCURRENT"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="DURING"/>
 *     <enumeration value="OVERLAP"/>
 *     <enumeration value="OVERLAP"/>
 *     <enumeration value="CHRG"/>
 *     <enumeration value="COST"/>
 *     <enumeration value="CHRG"/>
 *     <enumeration value="COST"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="CHRG"/>
 *     <enumeration value="COST"/>
 *     <enumeration value="CHRG"/>
 *     <enumeration value="COST"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="CREDIT"/>
 *     <enumeration value="DEBIT"/>
 *     <enumeration value="AUTH"/>
 *     <enumeration value="CAUS"/>
 *     <enumeration value="COVBY"/>
 *     <enumeration value="DRIV"/>
 *     <enumeration value="ELNK"/>
 *     <enumeration value="EVID"/>
 *     <enumeration value="EXACBY"/>
 *     <enumeration value="EXPL"/>
 *     <enumeration value="ITEMSLOC"/>
 *     <enumeration value="LIMIT"/>
 *     <enumeration value="META"/>
 *     <enumeration value="MFST"/>
 *     <enumeration value="NAME"/>
 *     <enumeration value="PREV"/>
 *     <enumeration value="REFR"/>
 *     <enumeration value="USE"/>
 *     <enumeration value="REFV"/>
 *     <enumeration value="RELVBY"/>
 *     <enumeration value="SPRT"/>
 *     <enumeration value="SPRTBND"/>
 *     <enumeration value="SUBJ"/>
 *     <enumeration value="SUMM"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ActRelationshipPertains")
@XmlEnum
public enum ActRelationshipPertains {

    PERT,
    EAE,
    EAS,
    EDU,
    EBS,
    ECW,
    CONCURRENT,
    SAE,
    SAS,
    SDU,
    SBS,
    SCW,
    DURING,
    OVERLAP,
    CHRG,
    COST,
    CREDIT,
    DEBIT,
    AUTH,
    CAUS,
    COVBY,
    DRIV,
    ELNK,
    EVID,
    EXACBY,
    EXPL,
    ITEMSLOC,
    LIMIT,
    META,
    MFST,
    NAME,
    PREV,
    REFR,
    USE,
    REFV,
    RELVBY,
    SPRT,
    SPRTBND,
    SUBJ,
    SUMM;

    public String value() {
        return name();
    }

    public static ActRelationshipPertains fromValue(String v) {
        return valueOf(v);
    }

}
