//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressUse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="AddressUse">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="AS"/>
 *     <enumeration value="BAD"/>
 *     <enumeration value="CONF"/>
 *     <enumeration value="DIR"/>
 *     <enumeration value="EC"/>
 *     <enumeration value="H"/>
 *     <enumeration value="HP"/>
 *     <enumeration value="HV"/>
 *     <enumeration value="MC"/>
 *     <enumeration value="PG"/>
 *     <enumeration value="PHYS"/>
 *     <enumeration value="PST"/>
 *     <enumeration value="PUB"/>
 *     <enumeration value="TMP"/>
 *     <enumeration value="WP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "AddressUse")
@XmlEnum
public enum AddressUse {

    AS,
    BAD,
    CONF,
    DIR,
    EC,
    H,
    HP,
    HV,
    MC,
    PG,
    PHYS,
    PST,
    PUB,
    TMP,
    WP;

    public String value() {
        return name();
    }

    public static AddressUse fromValue(String v) {
        return valueOf(v);
    }

}
