//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalendarCycleOneLetter.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="CalendarCycleOneLetter">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CW"/>
 *     <enumeration value="W"/>
 *     <enumeration value="CY"/>
 *     <enumeration value="Y"/>
 *     <enumeration value="D"/>
 *     <enumeration value="DM"/>
 *     <enumeration value="DW"/>
 *     <enumeration value="J"/>
 *     <enumeration value="H"/>
 *     <enumeration value="HD"/>
 *     <enumeration value="M"/>
 *     <enumeration value="MY"/>
 *     <enumeration value="N"/>
 *     <enumeration value="NH"/>
 *     <enumeration value="S"/>
 *     <enumeration value="SN"/>
 *     <enumeration value="D"/>
 *     <enumeration value="H"/>
 *     <enumeration value="J"/>
 *     <enumeration value="M"/>
 *     <enumeration value="N"/>
 *     <enumeration value="S"/>
 *     <enumeration value="W"/>
 *     <enumeration value="Y"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CalendarCycleOneLetter")
@XmlEnum
public enum CalendarCycleOneLetter {

    CW,
    W,
    CY,
    Y,
    D,
    DM,
    DW,
    J,
    H,
    HD,
    M,
    MY,
    N,
    NH,
    S,
    SN;

    public String value() {
        return name();
    }

    public static CalendarCycleOneLetter fromValue(String v) {
        return valueOf(v);
    }

}
