//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassNullFlavor.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ClassNullFlavor">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="ASKU"/>
 *     <enumeration value="MSK"/>
 *     <enumeration value="NA"/>
 *     <enumeration value="NASK"/>
 *     <enumeration value="NAV"/>
 *     <enumeration value="NI"/>
 *     <enumeration value="UNK"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ClassNullFlavor")
@XmlEnum
public enum ClassNullFlavor {

    ASKU,
    MSK,
    NA,
    NASK,
    NAV,
    NI,
    UNK;

    public String value() {
        return name();
    }

    public static ClassNullFlavor fromValue(String v) {
        return valueOf(v);
    }

}
