//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityClass">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="ANM"/>
 *     <enumeration value="CER"/>
 *     <enumeration value="CHEM"/>
 *     <enumeration value="CITY"/>
 *     <enumeration value="CONT"/>
 *     <enumeration value="COUNTRY"/>
 *     <enumeration value="COUNTY"/>
 *     <enumeration value="DEV"/>
 *     <enumeration value="ENT"/>
 *     <enumeration value="FOOD"/>
 *     <enumeration value="HCE"/>
 *     <enumeration value="HOLD"/>
 *     <enumeration value="LIV"/>
 *     <enumeration value="MAT"/>
 *     <enumeration value="MIC"/>
 *     <enumeration value="MMAT"/>
 *     <enumeration value="MODDV"/>
 *     <enumeration value="NAT"/>
 *     <enumeration value="NLIV"/>
 *     <enumeration value="ORG"/>
 *     <enumeration value="PLC"/>
 *     <enumeration value="PLNT"/>
 *     <enumeration value="PROVINCE"/>
 *     <enumeration value="PSN"/>
 *     <enumeration value="PUB"/>
 *     <enumeration value="RGRP"/>
 *     <enumeration value="STATE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityClass")
@XmlEnum
public enum EntityClass {

    ANM,
    CER,
    CHEM,
    CITY,
    CONT,
    COUNTRY,
    COUNTY,
    DEV,
    ENT,
    FOOD,
    HCE,
    HOLD,
    LIV,
    MAT,
    MIC,
    MMAT,
    MODDV,
    NAT,
    NLIV,
    ORG,
    PLC,
    PLNT,
    PROVINCE,
    PSN,
    PUB,
    RGRP,
    STATE;

    public String value() {
        return name();
    }

    public static EntityClass fromValue(String v) {
        return valueOf(v);
    }

}
