//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityClassManufacturedMaterial.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityClassManufacturedMaterial">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="MMAT"/>
 *     <enumeration value="CONT"/>
 *     <enumeration value="HOLD"/>
 *     <enumeration value="DEV"/>
 *     <enumeration value="CER"/>
 *     <enumeration value="MODDV"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityClassManufacturedMaterial")
@XmlEnum
public enum EntityClassManufacturedMaterial {

    MMAT,
    CONT,
    HOLD,
    DEV,
    CER,
    MODDV;

    public String value() {
        return name();
    }

    public static EntityClassManufacturedMaterial fromValue(String v) {
        return valueOf(v);
    }

}
