//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityClassOrganization.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityClassOrganization">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="ORG"/>
 *     <enumeration value="PUB"/>
 *     <enumeration value="STATE"/>
 *     <enumeration value="NAT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityClassOrganization")
@XmlEnum
public enum EntityClassOrganization {

    ORG,
    PUB,
    STATE,
    NAT;

    public String value() {
        return name();
    }

    public static EntityClassOrganization fromValue(String v) {
        return valueOf(v);
    }

}
