//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityNameUse.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityNameUse">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="A"/>
 *     <enumeration value="ABC"/>
 *     <enumeration value="ASGN"/>
 *     <enumeration value="C"/>
 *     <enumeration value="I"/>
 *     <enumeration value="IDE"/>
 *     <enumeration value="L"/>
 *     <enumeration value="OR"/>
 *     <enumeration value="P"/>
 *     <enumeration value="PHON"/>
 *     <enumeration value="R"/>
 *     <enumeration value="SNDX"/>
 *     <enumeration value="SRCH"/>
 *     <enumeration value="SYL"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityNameUse")
@XmlEnum
public enum EntityNameUse {

    A,
    ABC,
    ASGN,
    C,
    I,
    IDE,
    L,
    OR,
    P,
    PHON,
    R,
    SNDX,
    SRCH,
    SYL;

    public String value() {
        return name();
    }

    public static EntityNameUse fromValue(String v) {
        return valueOf(v);
    }

}
