//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityNamePartQualifierR2.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityNamePartQualifierR2">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="AC"/>
 *     <enumeration value="AD"/>
 *     <enumeration value="BR"/>
 *     <enumeration value="CL"/>
 *     <enumeration value="CON"/>
 *     <enumeration value="DEV"/>
 *     <enumeration value="FRM"/>
 *     <enumeration value="HOM"/>
 *     <enumeration value="IN"/>
 *     <enumeration value="INV"/>
 *     <enumeration value="LS"/>
 *     <enumeration value="MID"/>
 *     <enumeration value="NB"/>
 *     <enumeration value="PFX"/>
 *     <enumeration value="PR"/>
 *     <enumeration value="SCI"/>
 *     <enumeration value="SFX"/>
 *     <enumeration value="SP"/>
 *     <enumeration value="STR"/>
 *     <enumeration value="TMK"/>
 *     <enumeration value="USE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityNamePartQualifierR2")
@XmlEnum
public enum EntityNamePartQualifierR2 {

    AC,
    AD,
    BR,
    CL,
    CON,
    DEV,
    FRM,
    HOM,
    IN,
    INV,
    LS,
    MID,
    NB,
    PFX,
    PR,
    SCI,
    SFX,
    SP,
    STR,
    TMK,
    USE;

    public String value() {
        return name();
    }

    public static EntityNamePartQualifierR2 fromValue(String v) {
        return valueOf(v);
    }

}
