//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntityStatusActive.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="EntityStatusActive">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="active"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "EntityStatusActive")
@XmlEnum
public enum EntityStatusActive {

    @XmlEnumValue("active")
    ACTIVE("active");
    private final String value;

    EntityStatusActive(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EntityStatusActive fromValue(String v) {
        for (EntityStatusActive c: EntityStatusActive.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
