//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IVL_RTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="IVL_RTO">
 *   <complexContent>
 *     <extension base="{urn:hl7-org:v3}SXCM_RTO">
 *       <sequence>
 *         <element name="low" type="{urn:hl7-org:v3}IVXB_RTO" minOccurs="0"/>
 *         <element name="high" type="{urn:hl7-org:v3}IVXB_RTO" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IVL_RTO", propOrder = {
    "low",
    "high"
})
public class IVLRTO
    extends SXCMRTO
{

    protected IVXBRTO low;
    protected IVXBRTO high;

    /**
     * Gets the value of the low property.
     * 
     * @return
     *     possible object is
     *     {@link IVXBRTO }
     *     
     */
    public IVXBRTO getLow() {
        return low;
    }

    /**
     * Sets the value of the low property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVXBRTO }
     *     
     */
    public void setLow(IVXBRTO value) {
        this.low = value;
    }

    /**
     * Gets the value of the high property.
     * 
     * @return
     *     possible object is
     *     {@link IVXBRTO }
     *     
     */
    public IVXBRTO getHigh() {
        return high;
    }

    /**
     * Sets the value of the high property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVXBRTO }
     *     
     */
    public void setHigh(IVXBRTO value) {
        this.high = value;
    }

}
