//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:hl7-org:v3", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.hl7.v3;
