//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipationTargetDirect.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ParticipationTargetDirect">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="DIR"/>
 *     <enumeration value="ALY"/>
 *     <enumeration value="BBY"/>
 *     <enumeration value="CAT"/>
 *     <enumeration value="CSM"/>
 *     <enumeration value="DEV"/>
 *     <enumeration value="NRD"/>
 *     <enumeration value="RDV"/>
 *     <enumeration value="DON"/>
 *     <enumeration value="EXPAGNT"/>
 *     <enumeration value="EXPART"/>
 *     <enumeration value="EXPTRGT"/>
 *     <enumeration value="EXSRC"/>
 *     <enumeration value="PRD"/>
 *     <enumeration value="SBJ"/>
 *     <enumeration value="SPC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ParticipationTargetDirect")
@XmlEnum
public enum ParticipationTargetDirect {

    DIR,
    ALY,
    BBY,
    CAT,
    CSM,
    DEV,
    NRD,
    RDV,
    DON,
    EXPAGNT,
    EXPART,
    EXPTRGT,
    EXSRC,
    PRD,
    SBJ,
    SPC;

    public String value() {
        return name();
    }

    public static ParticipationTargetDirect fromValue(String v) {
        return valueOf(v);
    }

}
