//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParticipationPhysicalPerformer.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="ParticipationPhysicalPerformer">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="PRF"/>
 *     <enumeration value="DIST"/>
 *     <enumeration value="PPRF"/>
 *     <enumeration value="SPRF"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "ParticipationPhysicalPerformer")
@XmlEnum
public enum ParticipationPhysicalPerformer {

    PRF,
    DIST,
    PPRF,
    SPRF;

    public String value() {
        return name();
    }

    public static ParticipationPhysicalPerformer fromValue(String v) {
        return valueOf(v);
    }

}
