//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for POCD_MT000040UV02.Reference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="POCD_MT000040UV02.Reference">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040UV02.InfrastructureRoot.typeId" minOccurs="0"/>
 *         <element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="seperatableInd" type="{urn:hl7-org:v3}BL" minOccurs="0"/>
 *         <choice>
 *           <element name="externalAct" type="{urn:hl7-org:v3}POCD_MT000040UV02.ExternalAct"/>
 *           <element name="externalObservation" type="{urn:hl7-org:v3}POCD_MT000040UV02.ExternalObservation"/>
 *           <element name="externalProcedure" type="{urn:hl7-org:v3}POCD_MT000040UV02.ExternalProcedure"/>
 *           <element name="externalDocument" type="{urn:hl7-org:v3}POCD_MT000040UV02.ExternalDocument"/>
 *         </choice>
 *       </sequence>
 *       <attGroup ref="{urn:hl7-org:v3}InfrastructureRootAttributes"/>
 *       <attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       <attribute name="typeCode" use="required" type="{urn:hl7-org:v3}x_ActRelationshipExternalReference" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POCD_MT000040UV02.Reference", propOrder = {
    "realmCode",
    "typeId",
    "templateId",
    "seperatableInd",
    "externalAct",
    "externalObservation",
    "externalProcedure",
    "externalDocument"
})
public class POCDMT000040UV02Reference {

    protected List<CS> realmCode;
    protected POCDMT000040UV02InfrastructureRootTypeId typeId;
    protected List<II> templateId;
    protected BL seperatableInd;
    protected POCDMT000040UV02ExternalAct externalAct;
    protected POCDMT000040UV02ExternalObservation externalObservation;
    protected POCDMT000040UV02ExternalProcedure externalProcedure;
    protected POCDMT000040UV02ExternalDocument externalDocument;
    @XmlAttribute(name = "nullFlavor")
    protected NullFlavor nullFlavor;
    @XmlAttribute(name = "typeCode", required = true)
    protected XActRelationshipExternalReference typeCode;

    /**
     * Gets the value of the realmCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the realmCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     * 
     * 
     * @return
     *     The value of the realmCode property.
     */
    public List<CS> getRealmCode() {
        if (realmCode == null) {
            realmCode = new ArrayList<>();
        }
        return this.realmCode;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link POCDMT000040UV02InfrastructureRootTypeId }
     *     
     */
    public POCDMT000040UV02InfrastructureRootTypeId getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link POCDMT000040UV02InfrastructureRootTypeId }
     *     
     */
    public void setTypeId(POCDMT000040UV02InfrastructureRootTypeId value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the templateId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     * @return
     *     The value of the templateId property.
     */
    public List<II> getTemplateId() {
        if (templateId == null) {
            templateId = new ArrayList<>();
        }
        return this.templateId;
    }

    /**
     * Gets the value of the seperatableInd property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getSeperatableInd() {
        return seperatableInd;
    }

    /**
     * Sets the value of the seperatableInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setSeperatableInd(BL value) {
        this.seperatableInd = value;
    }

    /**
     * Gets the value of the externalAct property.
     * 
     * @return
     *     possible object is
     *     {@link POCDMT000040UV02ExternalAct }
     *     
     */
    public POCDMT000040UV02ExternalAct getExternalAct() {
        return externalAct;
    }

    /**
     * Sets the value of the externalAct property.
     * 
     * @param value
     *     allowed object is
     *     {@link POCDMT000040UV02ExternalAct }
     *     
     */
    public void setExternalAct(POCDMT000040UV02ExternalAct value) {
        this.externalAct = value;
    }

    /**
     * Gets the value of the externalObservation property.
     * 
     * @return
     *     possible object is
     *     {@link POCDMT000040UV02ExternalObservation }
     *     
     */
    public POCDMT000040UV02ExternalObservation getExternalObservation() {
        return externalObservation;
    }

    /**
     * Sets the value of the externalObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link POCDMT000040UV02ExternalObservation }
     *     
     */
    public void setExternalObservation(POCDMT000040UV02ExternalObservation value) {
        this.externalObservation = value;
    }

    /**
     * Gets the value of the externalProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link POCDMT000040UV02ExternalProcedure }
     *     
     */
    public POCDMT000040UV02ExternalProcedure getExternalProcedure() {
        return externalProcedure;
    }

    /**
     * Sets the value of the externalProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link POCDMT000040UV02ExternalProcedure }
     *     
     */
    public void setExternalProcedure(POCDMT000040UV02ExternalProcedure value) {
        this.externalProcedure = value;
    }

    /**
     * Gets the value of the externalDocument property.
     * 
     * @return
     *     possible object is
     *     {@link POCDMT000040UV02ExternalDocument }
     *     
     */
    public POCDMT000040UV02ExternalDocument getExternalDocument() {
        return externalDocument;
    }

    /**
     * Sets the value of the externalDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link POCDMT000040UV02ExternalDocument }
     *     
     */
    public void setExternalDocument(POCDMT000040UV02ExternalDocument value) {
        this.externalDocument = value;
    }

    /**
     * Gets the value of the nullFlavor property.
     * 
     * @return
     *     possible object is
     *     {@link NullFlavor }
     *     
     */
    public NullFlavor getNullFlavor() {
        return nullFlavor;
    }

    /**
     * Sets the value of the nullFlavor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NullFlavor }
     *     
     */
    public void setNullFlavor(NullFlavor value) {
        this.nullFlavor = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link XActRelationshipExternalReference }
     *     
     */
    public XActRelationshipExternalReference getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link XActRelationshipExternalReference }
     *     
     */
    public void setTypeCode(XActRelationshipExternalReference value) {
        this.typeCode = value;
    }

}
