//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationalOperator.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RelationalOperator">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CT"/>
 *     <enumeration value="EQ"/>
 *     <enumeration value="GE"/>
 *     <enumeration value="GN"/>
 *     <enumeration value="GT"/>
 *     <enumeration value="LE"/>
 *     <enumeration value="LT"/>
 *     <enumeration value="NE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RelationalOperator")
@XmlEnum
public enum RelationalOperator {

    CT,
    EQ,
    GE,
    GN,
    GT,
    LE,
    LT,
    NE;

    public String value() {
        return name();
    }

    public static RelationalOperator fromValue(String v) {
        return valueOf(v);
    }

}
