//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassSubstancePresence.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RoleClassSubstancePresence">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CONT"/>
 *     <enumeration value="INGR"/>
 *     <enumeration value="ACTI"/>
 *     <enumeration value="ACTIB"/>
 *     <enumeration value="ACTIM"/>
 *     <enumeration value="ACTIR"/>
 *     <enumeration value="ADJV"/>
 *     <enumeration value="ADTV"/>
 *     <enumeration value="BASE"/>
 *     <enumeration value="IACT"/>
 *     <enumeration value="COLR"/>
 *     <enumeration value="FLVR"/>
 *     <enumeration value="PRSV"/>
 *     <enumeration value="STBL"/>
 *     <enumeration value="MECH"/>
 *     <enumeration value="LOCE"/>
 *     <enumeration value="STOR"/>
 *     <enumeration value="PART"/>
 *     <enumeration value="ACTM"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RoleClassSubstancePresence")
@XmlEnum
public enum RoleClassSubstancePresence {

    CONT,
    INGR,
    ACTI,
    ACTIB,
    ACTIM,
    ACTIR,
    ADJV,
    ADTV,
    BASE,
    IACT,
    COLR,
    FLVR,
    PRSV,
    STBL,
    MECH,
    LOCE,
    STOR,
    PART,
    ACTM;

    public String value() {
        return name();
    }

    public static RoleClassSubstancePresence fromValue(String v) {
        return valueOf(v);
    }

}
