//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassOntological.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RoleClassOntological">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="EQUIV"/>
 *     <enumeration value="SAME"/>
 *     <enumeration value="SUBY"/>
 *     <enumeration value="GEN"/>
 *     <enumeration value="GRIC"/>
 *     <enumeration value="INST"/>
 *     <enumeration value="SUBS"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RoleClassOntological")
@XmlEnum
public enum RoleClassOntological {

    EQUIV,
    SAME,
    SUBY,
    GEN,
    GRIC,
    INST,
    SUBS;

    public String value() {
        return name();
    }

    public static RoleClassOntological fromValue(String v) {
        return valueOf(v);
    }

}
