//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClassRelationshipFormal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RoleClassRelationshipFormal">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="AFFL"/>
 *     <enumeration value="AGNT"/>
 *     <enumeration value="ASSIGNED"/>
 *     <enumeration value="COMPAR"/>
 *     <enumeration value="SGNOFF"/>
 *     <enumeration value="CON"/>
 *     <enumeration value="ECON"/>
 *     <enumeration value="NOK"/>
 *     <enumeration value="GUARD"/>
 *     <enumeration value="CIT"/>
 *     <enumeration value="COVPTY"/>
 *     <enumeration value="CLAIM"/>
 *     <enumeration value="NAMED"/>
 *     <enumeration value="DEPEN"/>
 *     <enumeration value="INDIV"/>
 *     <enumeration value="SUBSCR"/>
 *     <enumeration value="PROG"/>
 *     <enumeration value="CRINV"/>
 *     <enumeration value="CRSPNSR"/>
 *     <enumeration value="EMP"/>
 *     <enumeration value="MIL"/>
 *     <enumeration value="GUAR"/>
 *     <enumeration value="INVSBJ"/>
 *     <enumeration value="CASEBJ"/>
 *     <enumeration value="RESBJ"/>
 *     <enumeration value="LIC"/>
 *     <enumeration value="NOT"/>
 *     <enumeration value="PROV"/>
 *     <enumeration value="PAT"/>
 *     <enumeration value="PAYEE"/>
 *     <enumeration value="PAYOR"/>
 *     <enumeration value="POLHOLD"/>
 *     <enumeration value="QUAL"/>
 *     <enumeration value="SPNSR"/>
 *     <enumeration value="STD"/>
 *     <enumeration value="UNDWRT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RoleClassRelationshipFormal")
@XmlEnum
public enum RoleClassRelationshipFormal {

    AFFL,
    AGNT,
    ASSIGNED,
    COMPAR,
    SGNOFF,
    CON,
    ECON,
    NOK,
    GUARD,
    CIT,
    COVPTY,
    CLAIM,
    NAMED,
    DEPEN,
    INDIV,
    SUBSCR,
    PROG,
    CRINV,
    CRSPNSR,
    EMP,
    MIL,
    GUAR,
    INVSBJ,
    CASEBJ,
    RESBJ,
    LIC,
    NOT,
    PROV,
    PAT,
    PAYEE,
    PAYOR,
    POLHOLD,
    QUAL,
    SPNSR,
    STD,
    UNDWRT;

    public String value() {
        return name();
    }

    public static RoleClassRelationshipFormal fromValue(String v) {
        return valueOf(v);
    }

}
