//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleClass.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RoleClass">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="ACCESS"/>
 *     <enumeration value="ACTI"/>
 *     <enumeration value="ACTIB"/>
 *     <enumeration value="ACTIM"/>
 *     <enumeration value="ACTIR"/>
 *     <enumeration value="ACTM"/>
 *     <enumeration value="ADJV"/>
 *     <enumeration value="ADJY"/>
 *     <enumeration value="ADMM"/>
 *     <enumeration value="ADTV"/>
 *     <enumeration value="AFFL"/>
 *     <enumeration value="AGNT"/>
 *     <enumeration value="ALQT"/>
 *     <enumeration value="ASSIGNED"/>
 *     <enumeration value="BASE"/>
 *     <enumeration value="BIRTHPL"/>
 *     <enumeration value="BOND"/>
 *     <enumeration value="CAREGIVER"/>
 *     <enumeration value="CASEBJ"/>
 *     <enumeration value="CHILD"/>
 *     <enumeration value="CIT"/>
 *     <enumeration value="CLAIM"/>
 *     <enumeration value="COLR"/>
 *     <enumeration value="COMPAR"/>
 *     <enumeration value="CON"/>
 *     <enumeration value="CONC"/>
 *     <enumeration value="CONT"/>
 *     <enumeration value="CONY"/>
 *     <enumeration value="COVPTY"/>
 *     <enumeration value="CRED"/>
 *     <enumeration value="CRINV"/>
 *     <enumeration value="CRSPNSR"/>
 *     <enumeration value="DEATHPLC"/>
 *     <enumeration value="DEPEN"/>
 *     <enumeration value="DSDLOC"/>
 *     <enumeration value="DST"/>
 *     <enumeration value="ECON"/>
 *     <enumeration value="EMP"/>
 *     <enumeration value="EQUIV"/>
 *     <enumeration value="EXPAGTCAR"/>
 *     <enumeration value="EXPR"/>
 *     <enumeration value="EXPVECTOR"/>
 *     <enumeration value="FLVR"/>
 *     <enumeration value="FOMITE"/>
 *     <enumeration value="GEN"/>
 *     <enumeration value="GRIC"/>
 *     <enumeration value="GUAR"/>
 *     <enumeration value="GUARD"/>
 *     <enumeration value="HLD"/>
 *     <enumeration value="HLTHCHRT"/>
 *     <enumeration value="IACT"/>
 *     <enumeration value="IDENT"/>
 *     <enumeration value="INDIV"/>
 *     <enumeration value="INGR"/>
 *     <enumeration value="INST"/>
 *     <enumeration value="INVSBJ"/>
 *     <enumeration value="ISDLOC"/>
 *     <enumeration value="ISLT"/>
 *     <enumeration value="LIC"/>
 *     <enumeration value="LOCE"/>
 *     <enumeration value="MANU"/>
 *     <enumeration value="MBR"/>
 *     <enumeration value="MECH"/>
 *     <enumeration value="MIL"/>
 *     <enumeration value="MNT"/>
 *     <enumeration value="NAMED"/>
 *     <enumeration value="NOK"/>
 *     <enumeration value="NOT"/>
 *     <enumeration value="NURPRAC"/>
 *     <enumeration value="NURS"/>
 *     <enumeration value="OWN"/>
 *     <enumeration value="PA"/>
 *     <enumeration value="PART"/>
 *     <enumeration value="PAT"/>
 *     <enumeration value="PAYEE"/>
 *     <enumeration value="PAYOR"/>
 *     <enumeration value="PHYS"/>
 *     <enumeration value="POLHOLD"/>
 *     <enumeration value="PROG"/>
 *     <enumeration value="PROV"/>
 *     <enumeration value="PRS"/>
 *     <enumeration value="PRSV"/>
 *     <enumeration value="QUAL"/>
 *     <enumeration value="RESBJ"/>
 *     <enumeration value="RET"/>
 *     <enumeration value="RGPR"/>
 *     <enumeration value="ROL"/>
 *     <enumeration value="SAME"/>
 *     <enumeration value="SDLOC"/>
 *     <enumeration value="SGNOFF"/>
 *     <enumeration value="SPEC"/>
 *     <enumeration value="SPNSR"/>
 *     <enumeration value="STBL"/>
 *     <enumeration value="STD"/>
 *     <enumeration value="STOR"/>
 *     <enumeration value="SUBS"/>
 *     <enumeration value="SUBSCR"/>
 *     <enumeration value="SUBY"/>
 *     <enumeration value="TERR"/>
 *     <enumeration value="THER"/>
 *     <enumeration value="UNDWRT"/>
 *     <enumeration value="USED"/>
 *     <enumeration value="WRTE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RoleClass")
@XmlEnum
public enum RoleClass {

    ACCESS,
    ACTI,
    ACTIB,
    ACTIM,
    ACTIR,
    ACTM,
    ADJV,
    ADJY,
    ADMM,
    ADTV,
    AFFL,
    AGNT,
    ALQT,
    ASSIGNED,
    BASE,
    BIRTHPL,
    BOND,
    CAREGIVER,
    CASEBJ,
    CHILD,
    CIT,
    CLAIM,
    COLR,
    COMPAR,
    CON,
    CONC,
    CONT,
    CONY,
    COVPTY,
    CRED,
    CRINV,
    CRSPNSR,
    DEATHPLC,
    DEPEN,
    DSDLOC,
    DST,
    ECON,
    EMP,
    EQUIV,
    EXPAGTCAR,
    EXPR,
    EXPVECTOR,
    FLVR,
    FOMITE,
    GEN,
    GRIC,
    GUAR,
    GUARD,
    HLD,
    HLTHCHRT,
    IACT,
    IDENT,
    INDIV,
    INGR,
    INST,
    INVSBJ,
    ISDLOC,
    ISLT,
    LIC,
    LOCE,
    MANU,
    MBR,
    MECH,
    MIL,
    MNT,
    NAMED,
    NOK,
    NOT,
    NURPRAC,
    NURS,
    OWN,
    PA,
    PART,
    PAT,
    PAYEE,
    PAYOR,
    PHYS,
    POLHOLD,
    PROG,
    PROV,
    PRS,
    PRSV,
    QUAL,
    RESBJ,
    RET,
    RGPR,
    ROL,
    SAME,
    SDLOC,
    SGNOFF,
    SPEC,
    SPNSR,
    STBL,
    STD,
    STOR,
    SUBS,
    SUBSCR,
    SUBY,
    TERR,
    THER,
    UNDWRT,
    USED,
    WRTE;

    public String value() {
        return name();
    }

    public static RoleClass fromValue(String v) {
        return valueOf(v);
    }

}
