//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleLinkRelated.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="RoleLinkRelated">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="REL"/>
 *     <enumeration value="BACKUP"/>
 *     <enumeration value="CONT"/>
 *     <enumeration value="DIRAUTH"/>
 *     <enumeration value="IDENT"/>
 *     <enumeration value="INDAUTH"/>
 *     <enumeration value="PART"/>
 *     <enumeration value="REPL"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "RoleLinkRelated")
@XmlEnum
public enum RoleLinkRelated {

    REL,
    BACKUP,
    CONT,
    DIRAUTH,
    IDENT,
    INDAUTH,
    PART,
    REPL;

    public String value() {
        return name();
    }

    public static RoleLinkRelated fromValue(String v) {
        return valueOf(v);
    }

}
