//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *             The character string data type stands for text data,
 *             primarily intended for machine processing (e.g.,
 *             sorting, querying, indexing, etc.) Used for names,
 *             symbols, and formal expressions. The ST data type 
 * 	    may have it's data as either the text content of the 
 * 	    element, or in a value attribute, but not both.
 *          
 * 
 * <p>Java class for ST.r2b complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ST.r2b">
 *   <complexContent>
 *     <restriction base="{urn:hl7-org:v3}ED.r2b">
 *       <sequence>
 *         <element name="reference" type="{urn:hl7-org:v3}TEL" maxOccurs="0" minOccurs="0"/>
 *         <element name="thumbnail" type="{urn:hl7-org:v3}ED.r2b" maxOccurs="0" minOccurs="0"/>
 *         <element name="translation" type="{urn:hl7-org:v3}STTranslation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="value" type="{urn:hl7-org:v3}st" />
 *       <attribute name="representation" type="{urn:hl7-org:v3}BinaryDataEncoding" fixed="TXT" />
 *       <attribute name="mediaType" type="{urn:hl7-org:v3}cs" fixed="text/plain" />
 *       <attribute name="language" type="{urn:hl7-org:v3}cs" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ST.r2b")
public class STR2B
    extends EDR2B
{


}
