//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TelecommunicationCapabilities.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="TelecommunicationCapabilities">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="DATA"/>
 *     <enumeration value="FAX"/>
 *     <enumeration value="SMS"/>
 *     <enumeration value="TTY"/>
 *     <enumeration value="VOICE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "TelecommunicationCapabilities")
@XmlEnum
public enum TelecommunicationCapabilities {

    DATA,
    FAX,
    SMS,
    TTY,
    VOICE;

    public String value() {
        return name();
    }

    public static TelecommunicationCapabilities fromValue(String v) {
        return valueOf(v);
    }

}
