//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                      A thumbnail is an abbreviated rendition of the full
 *                      data. A thumbnail requires significantly fewer
 *                      resources than the full data, while still maintaining
 *                      some distinctive similarity with the full data. A
 *                      thumbnail is typically used with by-reference
 *                      encapsulated data. It allows a user to select data
 *                      more efficiently before actually downloading through
 *                      the reference.
 *                   
 * 
 * <p>Java class for thumbnail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="thumbnail">
 *   <complexContent>
 *     <restriction base="{urn:hl7-org:v3}ED">
 *       <sequence>
 *         <element name="reference" type="{urn:hl7-org:v3}TEL" minOccurs="0"/>
 *         <element name="thumbnail" type="{urn:hl7-org:v3}thumbnail" maxOccurs="0" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "thumbnail")
public class Thumbnail
    extends ED
{


}
