//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_ActRelationshipEntryRelationship.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="x_ActRelationshipEntryRelationship">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CAUS"/>
 *     <enumeration value="COMP"/>
 *     <enumeration value="GEVL"/>
 *     <enumeration value="MFST"/>
 *     <enumeration value="REFR"/>
 *     <enumeration value="RSON"/>
 *     <enumeration value="SAS"/>
 *     <enumeration value="SPRT"/>
 *     <enumeration value="SUBJ"/>
 *     <enumeration value="XCRPT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "x_ActRelationshipEntryRelationship")
@XmlEnum
public enum XActRelationshipEntryRelationship {

    CAUS,
    COMP,
    GEVL,
    MFST,
    REFR,
    RSON,
    SAS,
    SPRT,
    SUBJ,
    XCRPT;

    public String value() {
        return name();
    }

    public static XActRelationshipEntryRelationship fromValue(String v) {
        return valueOf(v);
    }

}
