//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.hl7.v3;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for x_ActMoodCompletionCriterion.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="x_ActMoodCompletionCriterion">
 *   <restriction base="{urn:hl7-org:v3}cs">
 *     <enumeration value="CRT"/>
 *     <enumeration value="DEF"/>
 *     <enumeration value="EVN"/>
 *     <enumeration value="EVN.CRT"/>
 *     <enumeration value="INT"/>
 *     <enumeration value="RQO"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "x_ActMoodCompletionCriterion")
@XmlEnum
public enum XActMoodCompletionCriterion {

    CRT("CRT"),
    DEF("DEF"),
    EVN("EVN"),
    @XmlEnumValue("EVN.CRT")
    EVN_CRT("EVN.CRT"),
    INT("INT"),
    RQO("RQO");
    private final String value;

    XActMoodCompletionCriterion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XActMoodCompletionCriterion fromValue(String v) {
        for (XActMoodCompletionCriterion c: XActMoodCompletionCriterion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
